[package]
name = "sigmf"
version = "0.1.0"
edition = "2024"
authors = ["FutureSDR Contributors <team@futuresdr.org>", "Loïc Fejoz <loic@fejoz.net>"]
license = "Apache-2.0 or MIT"
repository = "https://github.com/futuresdr/fsdr-blocks/"
description = "Crate for interfacing to SigMF files"
keywords = ["sdr", "radio", "dsp", "sigmf", "fileformat"]
categories = ["science"]
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["quickcheck"]
quickcheck=['dep:quickcheck']

[dependencies]
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
quickcheck = { workspace = true, optional = true }
uuid = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[dev-dependencies]
quickcheck_macros = { workspace = true }

[lib]
name = "sigmf"
path = "src/lib.rs"
